spring.application.name=gateway-application

#spring.cloud.gateway.routes[0].id=Employee-Management-System        # Can be any name
#spring.cloud.gateway.routes[0].uri=http://localhost:8011    # Must match actual host:port of service
#spring.cloud.gateway.routes[0].predicates[0]=Path=/emp/**
#spring.cloud.gateway.routes[0].predicates[1]=Path=/auth/**

# Route 1 - for /emp/**
spring.cloud.gateway.server.webflux.routes[0].id=employee-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8011
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/emp/**

spring.cloud.gateway.server.webflux.routes[1].id=auth-endpoint
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8011
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/auth/**


logging.level.org.springframework.cloud.gateway=DEBUG






